### ISSUE TITLE
Psst... Misspelling

### ISSUE THREAD

**Issue by vickinssl** [jtmorris/tweet-this#2]
There's a misspelling in the "Add Tweet This Shortcode" button that displays next to the Add Media button in the editor:

![screen shot 2016-06-02 at 3 25 43 pm](https://cloud.githubusercontent.com/assets/2117526/15759883/63ea1bb4-28d6-11e6-9ca0-ac14ec646b19.png)

**Comment by jtmorris** [comment]
Thank you for pointing this out. It has been fixed and will be pushed out in the next plugin update.
